In [154]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('/content/Alphabets_data.csv')

In [3]:
df

letter  xbox  ybox  width  height  onpix  xbar  ybar  x2bar  y2bar  \
0          T     2     8      3       5      1     8    13      0      6   
1          I     5    12      3       7      2    10     5      5      4   
2          D     4    11      6       8      6    10     6      2      6   
3          N     7    11      6       6      3     5     9      4      6   
4          G     2     1      3       1      1     8     6      6      6   
...      ...   ...   ...    ...     ...    ...   ...   ...    ...    ...   
19995      D     2     2      3       3      2     7     7      7      6   
19996      C     7    10      8       8      4     4     8      6      9   
19997      T     6     9      6       7      5     6    11      3      7   
19998      S     2     3      4       2      1     8     7      2      6   
19999      A     4     9      6       6      2     9     5      3      1   

       xybar  x2ybar  xy2bar  xedge  xedgey  yedge  yedgex  
0          6      10       8      0       8      0       8  
1         13       3       9      2       8      4      10  
2         10       3       7      3       7      3       9  
3          4       4      10      6      10      2       8  
4          6       5       9      1       7      5      10  
...      ...     ...     ...    ...     ...    ...     ...  
19995      6       6       4      2       8      3       7  
19996     12       9      13      2       9      3       7  
19997     11       9       5      2      12      2       4  
19998     10       6       8      1       9      5       8  
19999      8       1       8      2       7      2       8  

[20000 rows x 17 columns]

In [4]:
print(df.head())

  letter  xbox  ybox  width  height  onpix  xbar  ybar  x2bar  y2bar  xybar  \
0      T     2     8      3       5      1     8    13      0      6      6   
1      I     5    12      3       7      2    10     5      5      4     13   
2      D     4    11      6       8      6    10     6      2      6     10   
3      N     7    11      6       6      3     5     9      4      6      4   
4      G     2     1      3       1      1     8     6      6      6      6   

   x2ybar  xy2bar  xedge  xedgey  yedge  yedgex  
0      10       8      0       8      0       8  
1       3       9      2       8      4      10  
2       3       7      3       7      3       9  
3       4      10      6      10      2       8  
4       5       9      1       7      5      10  


In [5]:
print(df.tail())

      letter  xbox  ybox  width  height  onpix  xbar  ybar  x2bar  y2bar  \
19995      D     2     2      3       3      2     7     7      7      6   
19996      C     7    10      8       8      4     4     8      6      9   
19997      T     6     9      6       7      5     6    11      3      7   
19998      S     2     3      4       2      1     8     7      2      6   
19999      A     4     9      6       6      2     9     5      3      1   

       xybar  x2ybar  xy2bar  xedge  xedgey  yedge  yedgex  
19995      6       6       4      2       8      3       7  
19996     12       9      13      2       9      3       7  
19997     11       9       5      2      12      2       4  
19998     10       6       8      1       9      5       8  
19999      8       1       8      2       7      2       8  


In [6]:
print(df.info)

<bound method DataFrame.info of       letter  xbox  ybox  width  height  onpix  xbar  ybar  x2bar  y2bar  \
0          T     2     8      3       5      1     8    13      0      6   
1          I     5    12      3       7      2    10     5      5      4   
2          D     4    11      6       8      6    10     6      2      6   
3          N     7    11      6       6      3     5     9      4      6   
4          G     2     1      3       1      1     8     6      6      6   
...      ...   ...   ...    ...     ...    ...   ...   ...    ...    ...   
19995      D     2     2      3       3      2     7     7      7      6   
19996      C     7    10      8       8      4     4     8      6      9   
19997      T     6     9      6       7      5     6    11      3      7   
19998      S     2     3      4       2      1     8     7      2      6   
19999      A     4     9      6       6      2     9     5      3      1   

       xybar  x2ybar  xy2bar  xedge  xedgey  yedge  yed

In [7]:
print(df.describe())

               xbox          ybox         width       height         onpix  \
count  20000.000000  20000.000000  20000.000000  20000.00000  20000.000000   
mean       4.023550      7.035500      5.121850      5.37245      3.505850   
std        1.913212      3.304555      2.014573      2.26139      2.190458   
min        0.000000      0.000000      0.000000      0.00000      0.000000   
25%        3.000000      5.000000      4.000000      4.00000      2.000000   
50%        4.000000      7.000000      5.000000      6.00000      3.000000   
75%        5.000000      9.000000      6.000000      7.00000      5.000000   
max       15.000000     15.000000     15.000000     15.00000     15.000000   

               xbar          ybar         x2bar         y2bar         xybar  \
count  20000.000000  20000.000000  20000.000000  20000.000000  20000.000000   
mean       6.897600      7.500450      4.628600      5.178650      8.282050   
std        2.026035      2.325354      2.699968      2.38082

In [8]:
print(df.columns)

Index(['letter', 'xbox', 'ybox', 'width', 'height', 'onpix', 'xbar', 'ybar',
       'x2bar', 'y2bar', 'xybar', 'x2ybar', 'xy2bar', 'xedge', 'xedgey',
       'yedge', 'yedgex'],
      dtype='object')


In [9]:
print(df.dtypes)

letter    object
xbox       int64
ybox       int64
width      int64
height     int64
onpix      int64
xbar       int64
ybar       int64
x2bar      int64
y2bar      int64
xybar      int64
x2ybar     int64
xy2bar     int64
xedge      int64
xedgey     int64
yedge      int64
yedgex     int64
dtype: object


In [10]:
print(df.shape)

(20000, 17)


In [11]:
print("Dataset Shape:", df.shape)
print("Dataset Info:")
print(df.info())
print("Summary Statistics:")
print(df.describe())

Dataset Shape: (20000, 17)
Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 17 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   letter  20000 non-null  object
 1   xbox    20000 non-null  int64 
 2   ybox    20000 non-null  int64 
 3   width   20000 non-null  int64 
 4   height  20000 non-null  int64 
 5   onpix   20000 non-null  int64 
 6   xbar    20000 non-null  int64 
 7   ybar    20000 non-null  int64 
 8   x2bar   20000 non-null  int64 
 9   y2bar   20000 non-null  int64 
 10  xybar   20000 non-null  int64 
 11  x2ybar  20000 non-null  int64 
 12  xy2bar  20000 non-null  int64 
 13  xedge   20000 non-null  int64 
 14  xedgey  20000 non-null  int64 
 15  yedge   20000 non-null  int64 
 16  yedgex  20000 non-null  int64 
dtypes: int64(16), object(1)
memory usage: 2.6+ MB
None
Summary Statistics:
               xbox          ybox         width       height         onpix  \
count  20000

In [12]:
#missing values
print(df.isnull().sum())

letter    0
xbox      0
ybox      0
width     0
height    0
onpix     0
xbar      0
ybar      0
x2bar     0
y2bar     0
xybar     0
x2ybar    0
xy2bar    0
xedge     0
xedgey    0
yedge     0
yedgex    0
dtype: int64


In [40]:
# Display the number of samples
num_samples = df.shape[0]
print(f"Number of samples: {num_samples}")

Number of samples: 20000


In [41]:
# Display the number of features
num_features = df.shape[1] -1 #subtract 1 to exclude the target variable
print(f"Number of features: {num_features}")

Number of features: 16


In [42]:
# Display the number of classes
num_classes = df.iloc[:,-1].nunique()
print(f"Number of classes: {num_classes}")

Number of classes: 16


In [43]:
 #Display unique class labels
print(f"Unique classes: {df.iloc[:,-1].unique()}")

Unique classes: [ 8 10  9  7  6 11  4  5  3 12 13 14  1  2 15  0]


In [13]:
numeric_df = df.select_dtypes(include=[np.number])

In [14]:
means = numeric_df.mean()

In [15]:
df.fillna(df.mean, inplace=True)

In [16]:
actual_target_column_name = 'letter'
X = df.drop(actual_target_column_name, axis=1)
y = df[actual_target_column_name]

In [17]:
#Normalize the data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [18]:
# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [44]:
# Output summary
print("Training Set Shape:", X_train.shape)
print("Test Set Shape:", X_test.shape)
print("Classes:", np.unique(y))

Training Set Shape: (16000, 16)
Test Set Shape: (4000, 16)
Classes: ['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J' 'K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R'
 'S' 'T' 'U' 'V' 'W' 'X' 'Y' 'Z']


In [45]:
from sklearn.preprocessing import MinMaxScaler

In [46]:
# Select numerical columns for normalization (excluding the target variable)
numerical_cols = df.select_dtypes(include=np.number).columns[:-1]

In [47]:
# Initialize the MinMaxScaler
scaler = MinMaxScaler()

# Fit and transform the numerical features
df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

In [48]:
# Handle missing values (using mean imputation for numerical features)
for col in numerical_cols:
    if df[col].isnull().any():
        df[col].fillna(df[col].mean(), inplace=True)

In [49]:
# Alternatively, for categorical features (if any):
categorical_cols = df.select_dtypes(include='object').columns
for col in categorical_cols:
  if df[col].isnull().any():
    df[col].fillna(df[col].mode()[0], inplace=True)

In [52]:
print(df.head())
print(df.isnull().sum())

  letter      xbox      ybox  width    height     onpix      xbar      ybar  \
0      T  0.133333  0.533333    0.2  0.333333  0.066667  0.533333  0.866667   
1      I  0.333333  0.800000    0.2  0.466667  0.133333  0.666667  0.333333   
2      D  0.266667  0.733333    0.4  0.533333  0.400000  0.666667  0.400000   
3      N  0.466667  0.733333    0.4  0.400000  0.200000  0.333333  0.600000   
4      G  0.133333  0.066667    0.2  0.066667  0.066667  0.533333  0.400000   

      x2bar     y2bar     xybar    x2ybar    xy2bar     xedge    xedgey  \
0  0.000000  0.400000  0.400000  0.666667  0.533333  0.000000  0.533333   
1  0.333333  0.266667  0.866667  0.200000  0.600000  0.133333  0.533333   
2  0.133333  0.400000  0.666667  0.200000  0.466667  0.200000  0.466667   
3  0.266667  0.400000  0.266667  0.266667  0.666667  0.400000  0.666667   
4  0.400000  0.400000  0.400000  0.333333  0.600000  0.066667  0.466667   

      yedge  yedgex  
0  0.000000       8  
1  0.266667      10  
2  0.200

In [53]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import LabelBinarizer

In [54]:
X = df.iloc[:, 1:-1].values
y = df.iloc[:, -1].values

In [55]:
# One-hot encode the target variable if it's categorical
y = tf.keras.utils.to_categorical(y)

In [56]:
encoder = LabelBinarizer()  # Or use LabelEncoder for integer encoding
letter_encoded = encoder.fit_transform(df['letter'])

In [57]:
# Concatenate the encoded 'letter' column with other features
X = np.concatenate([letter_encoded, X], axis=1)

# Define the model
model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(X.shape[1],)))
model.add(Dense(32, activation='relu'))
model.add(Dense(y.shape[1], activation='softmax'))

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X, y, epochs=10, batch_size=32)

Epoch 1/10


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


625/625 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.3880 - loss: 1.9048
Epoch 2/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.4757 - loss: 1.3840
Epoch 3/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5099 - loss: 1.2690
Epoch 4/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5294 - loss: 1.2033
Epoch 5/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5512 - loss: 1.1426
Epoch 6/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5657 - loss: 1.1035
Epoch 7/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5700 - loss: 1.0850
Epoch 8/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5776 - loss: 1.0573
Epoch 9/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5986 - loss: 1.0243
Epoch 10/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5982 - loss: 1.0139


In [58]:
# Evaluate the model (optional)
loss, accuracy = model.evaluate(X,y, verbose = 0)
print(f"Loss: {loss:.4f}")
print(f"Accuracy: {accuracy:.4f}")

Loss: 0.9845
Accuracy: 0.6094


In [59]:
from sklearn.model_selection import train_test_split

In [60]:
# Model Implementation
X = df.iloc[:, 1:-1].values
y = df.iloc[:, -1].values

# One-hot encode the target variable if it's categorical
y = tf.keras.utils.to_categorical(y)

# One-hot encode or label encode the 'letter' column
encoder = LabelBinarizer()
letter_encoded = encoder.fit_transform(df['letter'])
X = np.concatenate([letter_encoded, X], axis=1)

# Divide the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [61]:
# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model using the training sets
model.fit(X_train, y_train, epochs=10, batch_size=3)

Epoch 1/10
5334/5334 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step - accuracy: 0.5852 - loss: 1.0285
Epoch 2/10
5334/5334 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step - accuracy: 0.6025 - loss: 1.0026
Epoch 3/10
5334/5334 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.6078 - loss: 0.9773
Epoch 4/10
5334/5334 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step - accuracy: 0.6236 - loss: 0.9446
Epoch 5/10
5334/5334 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step - accuracy: 0.6288 - loss: 0.9224
Epoch 6/10
5334/5334 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - accuracy: 0.6336 - loss: 0.9089
Epoch 7/10
5334/5334 ━━━━━━━━━━━━━━━━━━━━ 11s 2ms/step - accuracy: 0.6398 - loss: 0.8945
Epoch 8/10
5334/5334 ━━━━━━━━━━━━━━━━━━━━ 11s 2ms/step - accuracy: 0.6518 - loss: 0.8752
Epoch 9/10
5334/5334 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step - accuracy: 0.6525 - loss: 0.8666
Epoch 10/10
5334/5334 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step - accuracy: 0.6508 - loss: 0.8584


In [62]:
# Evaluate the model using the test sets
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"Test Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")

Test Loss: 0.8843
Test Accuracy: 0.6475


In [63]:
# Divide the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the model
model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(X_train.shape[1],)))
model.add(Dense(32, activation='relu'))
model.add(Dense(y_train.shape[1], activation='softmax'))  # Output layer with softmax

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model using the training sets
model.fit(X_train, y_train, epochs=10, batch_size=32)

Epoch 1/10


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.3645 - loss: 1.9262
Epoch 2/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4782 - loss: 1.4022
Epoch 3/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5010 - loss: 1.3000
Epoch 4/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.5203 - loss: 1.2285
Epoch 5/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5345 - loss: 1.1833
Epoch 6/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5490 - loss: 1.1405
Epoch 7/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5698 - loss: 1.0894
Epoch 8/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5778 - loss: 1.0699
Epoch 9/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5903 - loss: 1.0435
Epoch 10/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5862 - loss: 1.0333


In [64]:
# Evaluate the model using the test sets
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"Test Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")

Test Loss: 1.0376
Test Accuracy: 0.5943


In [65]:
from sklearn.metrics import classification_report

In [66]:
# Make predictions on the test set
y_pred = model.predict(X_test)

# Convert predicted probabilities to class labels (if needed)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true_classes = np.argmax(y_test, axis=1)

# you can calculate further metrics like precision, recall, F1-score, etc.

print(classification_report(y_true_classes, y_pred_classes))

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.00      0.00      0.00         4
           2       0.00      0.00      0.00         6
           3       0.00      0.00      0.00        31
           4       0.48      0.44      0.46        94
           5       0.51      0.25      0.33       196
           6       0.47      0.49      0.48       353
           7       0.56      0.49      0.52       712
           8       0.73      0.81      0.77      1596
           9       0.45      0.40      0.42       485
          10       0.40      0.52      0.46       308
          11       0.54      0.65      0.59       175
          12       0.00      0.00      0.00        29
          13       0.00      0.00      0.00         9
          14       0.00      0.00      0.00         1

    accuracy                           0.59      4000
   macro avg       0.28      0.27      

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [68]:
!pip install scikit-learn
!pip install --upgrade scikit-learn
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import accuracy_score

In [69]:
# Load the Iris dataset
X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [70]:
# Define the hyperparameter grid
param_grid = {
    'n_neighbors': [3, 5, 7],  # Number of neighbors
    'weights': ['uniform', 'distance'],  # Weight function
    'metric': ['euclidean', 'manhattan']  # Distance metric
}

In [71]:
# Initialize the k-NN model and GridSearchCV
knn = KNeighborsClassifier()
grid_search = GridSearchCV(knn, param_grid, cv=3, scoring='accuracy')
grid_search.fit(X_train, y_train)

# Test the best model
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)
print(f"Best Parameters: {grid_search.best_params_}")
print(f"Test Accuracy: {accuracy_score(y_test, y_pred):.4f}")

Best Parameters: {'metric': 'euclidean', 'n_neighbors': 3, 'weights': 'distance'}
Test Accuracy: 1.0000


In [72]:
!pip install scikeras

In [81]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import numpy as np
from sklearn.model_selection import RandomizedSearchCV

In [74]:
# Load dataset
df = load_iris()
X = df.data
y = df.target

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize Random Forest Classifier
model = RandomForestClassifier(random_state=42)

In [85]:
# Define hyperparameter grids
param_grid = {
    'n_estimators': [10, 50, 100, 200],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}
# Initialize and fit RandomizedSearchCV
random_search = RandomizedSearchCV(estimator=model, param_distributions=param_dist, n_iter=10, cv=5, n_jobs=-1, verbose=2, random_state=42)  # Try 10 random combinations
random_search.fit(X_train, y_train)




RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42),
                   n_jobs=-1,
                   param_distributions={'max_depth': [None, 10, 20, 30],
                                        'min_samples_leaf': array([1, 2, 3, 4]),
                                        'min_samples_split': array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]),
                                        'n_estimators': [10, 50, 100, 200]},
                   random_state=42, verbose=2)

In [79]:
random_search = RandomizedSearchCV(estimator=model, param_distributions=param_dist, n_iter=10,
                                      cv=5, n_jobs=-1, random_state=42, verbose=2)

In [86]:
# Randomized Search
param_dist = {
    'n_estimators': [10, 50, 100, 200],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': np.arange(2, 11),
    'min_samples_leaf': np.arange(1, 5)
}

random_search = RandomizedSearchCV(estimator=model, param_distributions=param_dist, n_iter=20,
                                   cv=5, n_jobs=-1, random_state=42, verbose=2)
random_search.fit(X_train, y_train)

# Display best parameters and accuracy
print("Randomized Search Best Parameters:", random_search.best_params_)
best_model_random = random_search.best_estimator_
y_pred_random = best_model_random.predict(X_test)
print("Randomized Search Test Accuracy:", accuracy_score(y_test, y_pred_random))

Randomized Search Best Parameters: {'n_estimators': 100, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_depth': 10}
Randomized Search Test Accuracy: 1.0


In [106]:
random_search = RandomizedSearchCV(estimator=model, param_distributions=param_dist, n_iter=10, cv=3, n_jobs=-1, verbose=2)

In [107]:

random_search.fit(X_train, y_train)

Fitting 3 folds for each of 10 candidates, totalling 30 fits


RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(random_state=42),
                   n_jobs=-1,
                   param_distributions={'max_depth': [None, 10, 20, 30],
                                        'min_samples_leaf': array([1, 2, 3, 4]),
                                        'min_samples_split': array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]),
                                        'n_estimators': [10, 50, 100, 200]},
                   verbose=2)

In [89]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [90]:
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [91]:
# Make predictions on the test set
y_pred = model.predict(X_test)

# y_pred already contains class labels, no need for argmax
y_pred_classes = y_pred
y_true_classes = y_test

In [92]:
# Calculate evaluation metrics
accuracy = accuracy_score(y_true_classes, y_pred_classes)
precision = precision_score(y_true_classes, y_pred_classes, average='weighted')
recall = recall_score(y_true_classes, y_pred_classes, average='weighted')
f1 = f1_score(y_true_classes, y_pred_classes, average='weighted')

In [93]:
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-score: {f1:.4f}")

print(classification_report(y_true_classes, y_pred_classes))

Accuracy: 1.0000
Precision: 1.0000
Recall: 1.0000
F1-score: 1.0000
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [109]:
from sklearn.metrics import classification_report
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import uniform
from sklearn.model_selection import GridSearchCV
from sklearn.neural_network import MLPClassifier

In [112]:
# Define the model with potential early stopping (if applicable)
model = MLPClassifier(max_iter=1000, early_stopping=True) # Example with early stopping

In [113]:
# Define a smaller hyperparameter grid (example)
param_grid = {
    'hidden_layer_sizes': [(50,), (100,)],  # Reduced options
    'activation': ['relu', 'tanh'],        # Reduced options
    'learning_rate_init': [0.001, 0.01],  # Reduced options
}


In [114]:

# Set up GridSearchCV with n_jobs and reduced cv
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=3, n_jobs=-1, verbose=2) # Reduced cv

# Fit the model
grid_search.fit(X_train, y_train)

Fitting 3 folds for each of 8 candidates, totalling 24 fits


GridSearchCV(cv=3, estimator=MLPClassifier(early_stopping=True, max_iter=1000),
             n_jobs=-1,
             param_grid={'activation': ['relu', 'tanh'],
                         'hidden_layer_sizes': [(50,), (100,)],
                         'learning_rate_init': [0.001, 0.01]},
             verbose=2)

In [117]:
# Initialize and fit GridSearchCV
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=3, n_jobs=-1, verbose=2, scoring='accuracy')
grid_search.fit(X_train, y_train)

# Display best parameters and accuracy
print("Grid Search Best Parameters:", grid_search.best_params_)

# Get the best model from GridSearchCV
best_model_grid = grid_search.best_estimator_ # Changed from grid_search.best to grid_search.best_estimator_


Fitting 3 folds for each of 8 candidates, totalling 24 fits
Grid Search Best Parameters: {'activation': 'relu', 'hidden_layer_sizes': (100,), 'learning_rate_init': 0.01}


In [118]:
# Evaluate the RandomizedSearchCV tuned model
random_predictions = best_model_random.predict(X_test)
random_accuracy = accuracy_score(y_test, random_predictions)
print(f"Randomized Search Tuned Model Accuracy: {random_accuracy:.4f}")

# Evaluate the GridSearchCV tuned model
grid_predictions = best_model_grid.predict(X_test)
grid_accuracy = accuracy_score(y_test, grid_predictions)
print(f"Grid Search Tuned Model Accuracy: {grid_accuracy:.4f}")

Randomized Search Tuned Model Accuracy: 1.0000
Grid Search Tuned Model Accuracy: 1.0000


In [119]:
# Further analysis (example):
# Get the best score from the grid search
grid_accuracy = grid_search.best_score_  # Assign the best accuracy to grid_accuracy

if grid_accuracy > default_accuracy:
    print("\nHyperparameter tuning with GridSearchCV improved the model's accuracy.")
    print(f"Improvement: {(grid_accuracy - default_accuracy):.4f}")
    print("Best parameters found:", grid_search.best_params_)

if random_accuracy > default_accuracy:
    print("\nHyperparameter tuning with RandomizedSearchCV improved the model's accuracy.")
    print(f"Improvement: {(random_accuracy - default_accuracy):.4f}")
    print("Best parameters found:", random_search.best_params_)

In [120]:
print("\nClassification Report for Default Model:")
print(classification_report(y_test, default_model_predictions))
print("\nClassification Report for Grid Search Tuned Model:")
print(classification_report(y_test, grid_predictions))
print("\nClassification Report for Randomized Search Tuned Model:")
print(classification_report(y_test, random_predictions))



Classification Report for Default Model:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30


Classification Report for Grid Search Tuned Model:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30


Classification Report for Randomized Search Tuned Model:
              precision    recall  f1-score   support

           0       1.00      1.

In [122]:
model.fit(X_train, y_train)  # Add this line to fit the model

y_pred = model.predict(X_test)

In [123]:


# Calculate evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [124]:

print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-score: {f1:.4f}")

print(classification_report(y_test, y_pred))

Accuracy: 0.3000
Precision: 0.0900
Recall: 0.3000
F1-score: 0.1385
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        10
           1       0.30      1.00      0.46         9
           2       0.00      0.00      0.00        11

    accuracy                           0.30        30
   macro avg       0.10      0.33      0.15        30
weighted avg       0.09      0.30      0.14        30



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [125]:
# Evaluate the default model
default_model = RandomForestClassifier(random_state=42)
default_model.fit(X_train, y_train)
default_model_predictions = default_model.predict(X_test)

print("\nClassification Report for Default Model:")
print(classification_report(y_test, default_model_predictions))

default_accuracy = accuracy_score(y_test, default_model_predictions)
print(f"Default Model Accuracy: {default_accuracy:.4f}")


Classification Report for Default Model:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Default Model Accuracy: 1.0000


In [ ]:
# No code changes are needed as the provided code already demonstrates proficiency in data preprocessing and model development.
# The code performs data exploration, preprocessing (scaling, handling missing values),
# implements a neural network and a KNN model, performs hyperparameter tuning using GridSearchCV and RandomizedSearchCV,
# and evaluates models with metrics like accuracy, precision, recall, and F1-score.
# The code also includes a comparison of the default model, grid-searched model, and randomized-searched model.

# To further enhance the code, one might consider:
# 1. Feature engineering: Explore creating new features or transforming existing ones to improve model performance.
# 2. More robust model selection: Test a wider range of models and compare their performance.
# 3. Cross-validation: Employ more rigorous cross-validation techniques (e.g., stratified k-fold) for a better estimate of model generalization.
# 4. Visualization: Create visualizations of the data and model results to gain further insights.
# 5. Error analysis: Investigate misclassified examples to identify patterns and potential weaknesses in the model or data.

In [126]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

In [127]:
# Define a function for hyperparameter tuning
def tune_hyperparameters(model, param_dist, search_type='grid', n_iter=None):
    """
    Performs hyperparameter tuning using GridSearchCV or RandomizedSearchCV.

    Args:
        model: The model to tune.
        param_dist: The hyperparameter distribution to search.
        search_type: 'grid' for GridSearchCV, 'random' for RandomizedSearchCV.
        n_iter: Number of iterations for RandomizedSearchCV (ignored for GridSearchCV).
    Returns:
         A tuple containing the best model and the best hyperparameters.
    """
    if search_type == 'grid':
        search = GridSearchCV(estimator=model, param_grid=param_dist, cv=5, n_jobs=-1, verbose=2)
    elif search_type == 'random':
        search = RandomizedSearchCV(estimator=model, param_distributions=param_dist, n_iter=n_iter, cv=5, n_jobs=-1, random_state=42, verbose=2)
    else:
        raise ValueError("Invalid search_type. Choose 'grid' or 'random'.")
    search.fit(X_train, y_train)
    print(f"{search_type.capitalize()} Search Best Parameters:", search.best_params_)
    return search.best_estimator_, search.best_params_

In [129]:
from tensorflow.keras.utils import to_categorical

In [130]:
def evaluate_model(model, X_test, y_test):
    """Evaluates a model and prints classification metrics."""
    y_pred = model.predict(X_test)

    # The RandomForestClassifier directly predicts class labels,
    # so there's no need to use argmax here
    y_pred_classes = y_pred

    # Convert predicted probabilities to class labels using argmax
    y_pred_classes = np.argmax(y_pred, axis=1)

    # y_true_classes is already in the correct format (one-hot encoded)
    # Convert it to class labels using argmax
    y_true_classes = np.argmax(y_test, axis=1)

    print(classification_report(y_true_classes, y_pred_classes))
    print(f"Accuracy: {accuracy_score(y_true_classes, y_pred_classes):.4f}")
    print(f"Precision: {precision_score(y_true_classes, y_pred_classes, average='weighted'):.4f}")
    print(f"Recall: {recall_score(y_true_classes, y_pred_classes, average='weighted'):.4f}")
    print(f"F1-score: {f1_score(y_true_classes, y_pred_classes, average='weighted'):.4f}")
    return accuracy_score(y_true_classes, y_pred_classes)

In [131]:
y_train = to_categorical(y_train)

# One-hot encode the target variable (y_test) for evaluation
y_test = to_categorical(y_test)

# ... (rest of the code) ...

#Neural Network Model
nn_model = Sequential()
nn_model.add(Dense(64, activation='relu', input_shape=(X_train.shape[1],)))
nn_model.add(Dense(32, activation='relu'))
nn_model.add(Dense(y_train.shape[1], activation='softmax')) # Now y_train.shape[1] is valid
nn_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
nn_model.fit(X_train, y_train, epochs=10, batch_size=32, verbose=0)

nn_accuracy = evaluate_model(nn_model, X_test, y_test)

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.22      0.36         9
           2       0.61      1.00      0.76        11

    accuracy                           0.77        30
   macro avg       0.87      0.74      0.71        30
weighted avg       0.86      0.77      0.72        30

Accuracy: 0.7667
Precision: 0.8574
Recall: 0.7667
F1-score: 0.7206


In [132]:
def evaluate_model(model, X_test, y_test):
    """Evaluates a model and prints classification metrics."""
    y_pred = model.predict(X_test)

    # The RandomForestClassifier directly predicts class labels,

    y_pred_classes = y_pred

    # Convert one-hot encoded y_test to class labels using argmax
    y_true_classes = np.argmax(y_test, axis=1)

    print(classification_report(y_true_classes, y_pred_classes))
    print(f"Accuracy: {accuracy_score(y_true_classes, y_pred_classes):.4f}")
    print(f"Precision: {precision_score(y_true_classes, y_pred_classes, average='weighted'):.4f}")
    print(f"Recall: {recall_score(y_true_classes, y_pred_classes, average='weighted'):.4f}")
    print(f"F1-score: {f1_score(y_true_classes, y_pred_classes, average='weighted'):.4f}")
    return accuracy_score(y_true_classes, y_pred_classes)

In [137]:
# KNN Model
knn_model = KNeighborsClassifier()
knn_param_grid = {
    'n_neighbors': [3, 5, 7],
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean', 'manhattan']
}
knn_grid_search = GridSearchCV(knn_model, knn_param_grid, cv=5, scoring='accuracy', verbose=0)
knn_grid_search.fit(X_train, np.argmax(y_train, axis=1))

best_knn_model = knn_grid_search.best_estimator_
knn_accuracy = evaluate_model(best_knn_model, X_test, y_test)

print("\nOverall Model Performance Comparison")
print(f"- Neural Network Accuracy: {nn_accuracy:.4f}")
print(f"- KNN Accuracy: {knn_accuracy:.4f}")


              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Accuracy: 1.0000
Precision: 1.0000
Recall: 1.0000
F1-score: 1.0000

Overall Model Performance Comparison
- Neural Network Accuracy: 0.7667
- KNN Accuracy: 1.0000


In [147]:
print("\nOverall Model Performance Comparison:")
print(f"- Neural Network Accuracy: {nn_accuracy:.4f}") # Assuming nn_accuracy is calculated and defined
print(f"- KNN Accuracy: {knn_accuracy:.4f}")         # Assuming knn_accuracy is calculated and defined





Overall Model Performance Comparison:
- Neural Network Accuracy: 0.7667
- KNN Accuracy: 1.0000


In [148]:


# Desired columns for feature extraction
desired_columns = ['xbox', 'ybox', 'width', 'high', 'onpix', 'xbar', 'ybar', 'x2bar', 'y2bar', 'xybar', 'x2ybr', 'xy2br']

In [26]:
desired_columns = ['x-box', 'y-box', 'width', 'height', 'onpix', 'x-bar', 'y-bar', 'x2bar', 'y2bar', 'xybar', 'x2ybr', 'xy2br']

# Check and select only existing columns
existing_columns = [col for col in desired_columns if col in df.columns]

In [150]:
# Splitting the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [151]:
# Displaying the results
print("Training Features (X_train):")
print(X_train)
print("\nTest Features (X_test):")
print(X_test)
print("\nTraining Target (y_train):")
print(y_train)
print("\nTest Target (y_test):")
print(y_test)

Training Features (X_train):
[[4.6 3.6 1.  0.2]
 [5.7 4.4 1.5 0.4]
 [6.7 3.1 4.4 1.4]
 [4.8 3.4 1.6 0.2]
 [4.4 3.2 1.3 0.2]
 [6.3 2.5 5.  1.9]
 [6.4 3.2 4.5 1.5]
 [5.2 3.5 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.2 4.1 1.5 0.1]
 [5.8 2.7 5.1 1.9]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [5.4 3.9 1.3 0.4]
 [5.4 3.7 1.5 0.2]
 [5.5 2.4 3.7 1. ]
 [6.3 2.8 5.1 1.5]
 [6.4 3.1 5.5 1.8]
 [6.6 3.  4.4 1.4]
 [7.2 3.6 6.1 2.5]
 [5.7 2.9 4.2 1.3]
 [7.6 3.  6.6 2.1]
 [5.6 3.  4.5 1.5]
 [5.1 3.5 1.4 0.2]
 [7.7 2.8 6.7 2. ]
 [5.8 2.7 4.1 1. ]
 [5.2 3.4 1.4 0.2]
 [5.  3.5 1.3 0.3]
 [5.1 3.8 1.9 0.4]
 [5.  2.  3.5 1. ]
 [6.3 2.7 4.9 1.8]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.1 3.3 1.7 0.5]
 [5.6 2.7 4.2 1.3]
 [5.1 3.4 1.5 0.2]
 [5.7 3.  4.2 1.2]
 [7.7 3.8 6.7 2.2]
 [4.6 3.2 1.4 0.2]
 [6.2 2.9 4.3 1.3]
 [5.7 2.5 5.  2. ]
 [5.5 4.2 1.4 0.2]
 [6.  3.  4.8 1.8]
 [5.8 2.7 5.1 1.9]
 [6.  2.2 4.  1. ]
 [5.4 3.  4.5 1.5]
 [6.2 3.4 5.4 2.3]
 [5.5 2.3 4.  1.3]
 [5.4 3.9 1.7 0.4]
 [5.  2.3 3.3 1. ]
 [6.4 2.7 5.3 1.9]
 [

In [152]:
# Initialize the model
model = RandomForestClassifier(random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 100.00%
